### ISSUE TITLE
asreview.datasets.BaseDataSet.from_config incomplete

### ISSUE THREAD

**Issue by jteijema** [asreview/template-extension-new-dataset#1]
Looking at the docs, I see `asreview.datasets.BaseDataSet.from_config` explained like this:

`config_file (str, dict) – Can be a link to a config file or one on the disk. Another option is to supply a dictionary with the metadata.`

To me, it would not be clear for a user what the config file or dictionary would look like. Nor is it clear to me 🥲 .

**Comment by J535D165** [comment]
An example is available now in the plugin, but let's document the example. JSONSchema might be useful here.

**Comment by jteijema** [comment]
Solved in #8
